POST http://localhost:8015/proxy/https://api.anthropic.com/v1/messages
anthropic-version: 2023-06-01
anthropic-beta: tools-2024-04-04
x-api-key: nanananere
Content-Type: application/json

{
    "model": "claude-3-opus-20240229",
    "max_tokens": 1024,
    "tools": [
        {
            "name": "get_weather",
            "description": "Get the current weather in a given location",
            "input_schema": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA"
                    }
                },
                "required": [
                    "location"
                ]
            }
        }
    ],
    "messages": [
        {
            "role": "user",
            "content": "What is the weather like in San Francisco?"
        }
    ]
}
